import Img1 from '../../images/node/node1.png'
import Img2 from '../../images/node/node2.png'
import Img3 from '../../images/node/node3.png'
import Img4 from '../../images/node/node4.png'
import Img5 from '../../images/node/node5.png'
import Img6 from '../../images/node/node6.png'
import Img7 from '../../images/node/node7.png'
import ImgP1 from '../../images/django/django1.png'
import ImgP2 from '../../images/django/django2.png'
import ImgP3 from '../../images/django/django3.png'
import ImgP4 from '../../images/django/django4.png'
import ImgP5 from '../../images/django/django5.png'
import ImgP6 from '../../images/django/django6.png'
import ImgP7 from '../../images/django/django7.png'
import pc1 from '../../images/pc/acountant1.png'
import pc2 from '../../images/pc/acountant2.png'
import pc3 from '../../images/pc/acountant3.png'
import pc4 from '../../images/pc/acountant4.png'
import pc5 from '../../images/pc/acountant5.png'
import pc6 from '../../images/pc/acountant6.png'
import pc7 from '../../images/pc/acountant7.png'

export const jsImages=[Img1,Img2,Img3,Img4,Img5,Img6,Img7]
export const pythonImages=[ImgP1,ImgP2,ImgP3,ImgP4,ImgP5,ImgP6,ImgP7]
export const pcImages =[pc1,pc2,pc3,pc4,pc5,pc6,pc7]